name: 'platformio-env'
description: 'Install Platform.IO environment'
runs:
  using: "composite"
  steps:
    - id: install-platformio-env
      shell: bash
      run: |
        apt update
        export DEBIAN_FRONTEND=noninteractive
        apt install -y git curl python3 python3-pip python3-venv git cmake
        curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
        python3 get-platformio.py
        echo 'export PATH=$PATH:~/.platformio/penv/bin' >> ~/.bashrc

