name: CI_Examples

on:
    pull_request:
      branches:
        - '**'

jobs:

    micro_ros_platformio:
        runs-on: ubuntu-20.04
        container: ubuntu:20.04

        strategy:
          fail-fast: false
          matrix:
            example: [addtwoints_service, publisher_ethernet, publisher_serial, publisher_wifi, reconnection_example, subscriber, subscriber_twist, time_sync]
        steps:
        - uses: actions/checkout@v3
          with:
            path: repo
        - name: Install environment
          uses: ./repo/.github/actions/platformio-env
        - name: Build examples
          shell: bash
          run: |
            export PATH=$PATH:~/.platformio/penv/bin
            cd repo/examples/${{ matrix.example }}
            pio run
